services:
  # バックエンドサービス
  - type: web
    name: note-backend
    env: python
    region: singapore  # アジア圏で低レイテンシー
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    healthCheckPath: /health  # ヘルスチェックエンドポイント
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        sync: false  # Renderダッシュボードで設定
      - key: GOOGLE_CLOUD_PROJECT
        sync: false  # Renderダッシュボードで設定
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false  # Renderダッシュボードで設定
      - key: PORT
        value: 5001
      - key: HOST
        value: 0.0.0.0
      - key: CORS_ORIGINS
        sync: false  # Renderダッシュボードで設定

    # スケーリング設定
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
      targetCPUPercent: 80
